# Generated by Django 4.2.21 on 2025-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservice',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
