# Generated by Django 4.2.21 on 2025-05-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccesapp', '0002_alter_publicservice_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('publicservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencyfeedbacks', to='ccesapp.publicservice')),
            ],
        ),
    ]
