# Generated by Django 4.2.21 on 2025-05-20 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccesapp', '0003_agencyfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
