# Generated by Django 4.2.21 on 2025-05-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccesapp', '0004_agencyfeedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('nid', models.CharField(max_length=16, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('publicservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedashboards', to='ccesapp.publicservice')),
            ],
        ),
    ]
