# Generated by Django 4.2.21 on 2025-05-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccesapp', '0005_servicedashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedashboard',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicedashboard',
            name='publicservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceadmin', to='ccesapp.publicservice'),
        ),
    ]
